set(VTK_RENDERING_BACKEND "OpenGL2"
  CACHE STRING "Rendering backend for VTK."
)

set_property(CACHE VTK_RENDERING_BACKEND
  PROPERTY STRINGS
    OpenGL
    OpenGL2
)

superbuild_add_project(vtk
  DEBUGGABLE
  DEFAULT_ON
  DEPENDS tbb

  CMAKE_ARGS
    "-DBUILD_TESTING:BOOL=OFF"
    "-DBUILD_SHARED_LIBS:BOOL=OFF"
    "-DBUILD_EXAMPLES:BOOL=OFF"
    "-DModule_vtkRenderingExternal:BOOL=ON"
    "-DVTK_RENDERING_BACKEND:STRING=${VTK_RENDERING_BACKEND}"
    "-DVTK_SMP_IMPLEMENTATION_TYPE:STRING=TBB"
    "-DTBB_ROOT:PATH=<INSTALL_DIR>"
)
