superbuild_add_project(vtk
  DEBUGGABLE
  DEFAULT_ON
  DEPENDS tbb

  CMAKE_ARGS
    "-DBUILD_TESTING:BOOL=OFF"
    "-DBUILD_SHARED_LIBS:BOOL=OFF"
    "-DBUILD_EXAMPLES:BOOL=OFF"
    "-DModule_vtkRenderingExternal:BOOL=ON"
    "-DVTK_RENDERING_BACKEND:STRING=OpenGL2"
    "-DVTK_SMP_IMPLEMENTATION_TYPE:STRING=TBB"
    "-DTBB_ROOT:PATH=<INSTALL_DIR>"
)
